[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
notan = "0.14.0"
rand = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
ewebsock = "0.8"
shared = { path = "../shared" }

[package.metadata.notan.assets]
search = ["assets"]

[target.'wasm32-unknown-unknown'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
web-sys = { version = "0.3", features = ["Window", "Location"] }
